# Generated by Django 5.2.7 on 2026-04-11 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(default='', max_length=50)),
                ('relationship', models.CharField(blank=True, choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('PARENT', 'Parent')], max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'pending'), ('retired', 'Retired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_prefix', models.CharField(default='KRO-', max_length=10, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=50)),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(blank=True, max_length=255)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(default='UK', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('house_number', 'line_1', 'town', 'postcode')},
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('open', 'Open'), ('settled', 'Settled'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='received', max_length=16)),
                ('claimer', models.CharField(default='', max_length=200)),
                ('causer_full_name', models.CharField(default='', max_length=200)),
                ('cause_type', models.CharField(choices=[('member', 'Member'), ('dependant', 'Dependant')], default='dependant', max_length=40)),
                ('claimer_is_next_of_kin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_created', to=settings.AUTH_USER_MODEL)),
                ('causer_dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_claims', to='members.dependant')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('retired', 'Retired')], default='pending', max_length=16)),
                ('member_uid', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('uid_assigned', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField(default=False, help_text='Allow member to add/edit dependants')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.organization')),
            ],
        ),
        migrations.AddField(
            model_name='dependant',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='members.member'),
        ),
        migrations.CreateModel(
            name='ClaimRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(default='', max_length=200)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_registers', to='members.claim')),
                ('paid_members', models.ManyToManyField(blank=True, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='members.claim')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_records', to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='members.member'),
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='member_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='members.claim')),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.dependant')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(default='', max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('member_uid_snapshot', models.CharField(blank=True, max_length=64)),
                ('full_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_type', models.CharField(choices=[('membership', 'Membership Fee'), ('subscription', 'Subscription'), ('claim', 'Claim Payment'), ('other', 'Other')], max_length=32)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('external_payment_id', models.CharField(blank=True, help_text='Stripe/Paypal ID etc.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('manual', 'Manual (Bank Transfer)'), ('card', 'Card Payment')], default='manual', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_status_change', 'Member Status Change'), ('dependant_update', 'Dependant Update'), ('nok_update', 'Next Of Kin Update'), ('payment_created', 'Payment Created'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('claim_approved', 'Claim Approved')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='Short message describing the action')),
                ('description', models.TextField(blank=True, help_text='Detailed explanation (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, help_text='User/admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_member', models.ForeignKey(blank=True, help_text='Member affected by this action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='members.member')),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='members.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('days', models.PositiveIntegerField(default=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('request_type', models.CharField(choices=[('membership', 'Membership'), ('subscription', 'Subscription'), ('claim', 'Claim'), ('other', 'Other')], default='claim', max_length=32)),
                ('viewable_by_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='members.claim')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='members.member')),
                ('paid_members', models.ManyToManyField(blank=True, related_name='paid_payment_requests', to='members.member')),
                ('selected_members', models.ManyToManyField(blank=True, related_name='selected_payment_requests', to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.paymentrequest'),
        ),
        migrations.CreateModel(
            name='MemberPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='members.member')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_statuses', to='members.paymentrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='members_pay_status_0a9ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='members_pay_payment_f18111_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='members_pay_paid_at_904bfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberpaymentstatus',
            unique_together={('member', 'payment_request')},
        ),
    ]
