# Generated by Django 5.2.7 on 2026-04-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_address_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.address'),
        ),
    ]
