# Generated by Django 5.2.7 on 2026-04-11 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_address_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address_fk',
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(help_text='House number or name', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.address'),
        ),
    ]
