# Generated by Django 5.2.7 on 2026-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_address_fk_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Manual (Bank Transfer)'), ('card', 'Card (Stripe)'), ('both', 'Both (User Chooses)')], default='both', max_length=10),
        ),
    ]
