# Generated by Django 5.2.7 on 2026-04-13 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_paymentrequest_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='members_pay_status_0a9ba1_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='members_pay_payment_f18111_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='members_pay_paid_at_904bfe_idx',
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('member', 'payment_request')},
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='payment_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.paymentrequest'),
        ),
    ]
