# Generated by Django 5.2.7 on 2026-04-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_paymentauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'Manual (Bank Transfer)'), ('card', 'Card (Stripe)'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
