# Generated by Django 5.2.7 on 2026-04-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
