# Generated by Django 5.2.7 on 2026-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_accountlock_claimsettlement_loginattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_edit_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
