# Generated by Django 5.2.7 on 2026-04-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_can_edit_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
