# Generated by Django 5.2.7 on 2026-04-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_portal_access_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
