# Generated by Django 5.2.7 on 2026-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auditlog_is_high_risk_alter_auditlog_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='retirement_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
