# Generated by Django 5.2.7 on 2026-05-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_member_retirement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
