# Generated by Django 5.2.7 on 2026-05-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_claim_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
