# Generated by Django 5.2.7 on 2026-05-02 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_payment_updated_at_paymentrequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimrecord',
            name='settlement_date',
        ),
        migrations.AddField(
            model_name='claim',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claimsettlement',
            name='settlement_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
