# Generated by Django 5.2.7 on 2026-05-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_remove_claimrecord_settlement_date_claim_settled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimsettlement',
            name='deductions',
        ),
        migrations.CreateModel(
            name='ClaimSettlementDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_items', to='members.claimsettlement')),
            ],
        ),
    ]
