# Generated by Django 5.2.7 on 2026-05-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_claimsettlement_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimsettlement',
            name='processed_by',
        ),
    ]
