# Generated by Django 5.2.7 on 2026-05-04 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_remove_claimsettlement_processed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='claim',
            field=models.ForeignKey(blank=True, help_text='Attach document to a specific claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='members.claim'),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='dependant',
            field=models.ForeignKey(blank=True, help_text='Attach document to a dependant if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.dependant'),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='file',
            field=models.FileField(upload_to='member_documents/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.dependant')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='members.member')),
            ],
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='document_request',
            field=models.ForeignKey(blank=True, help_text='If uploaded in response to admin request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_documents', to='members.documentrequest'),
        ),
    ]
