# Generated by Django 5.2.7 on 2026-05-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_memberdocument_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsettlement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
    ]
