# Generated by Django 5.2.7 on 2026-05-11 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_paymentrequest_is_reconciled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='can_resubmit',
            field=models.BooleanField(default=False, help_text='Allow member to upload replacement document'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Documents are private and only viewable by the owning member and admins.'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided when document is rejected'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_member_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='memberdocument',
            index=models.Index(fields=['member', 'status'], name='members_mem_member__9fda91_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdocument',
            index=models.Index(fields=['uploaded_at'], name='members_mem_uploade_0e4e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='memberdocument',
            index=models.Index(fields=['status'], name='members_mem_status_a2bedc_idx'),
        ),
    ]
