# Generated by Django 5.2.7 on 2026-05-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_emailverification_magiclogintoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
