# Generated by Django 5.2.7 on 2026-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_memberdocument_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gdpr_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='gdpr_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gdpr_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gdpr_version',
            field=models.CharField(default='v1', max_length=20),
        ),
    ]
