# Generated by Django 5.2.7 on 2026-05-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_member_gdpr_consent_member_gdpr_consent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16),
        ),
    ]
