# Generated by Django 5.2.7 on 2026-05-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_paymentrequest_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
