# Generated by Django 5.2.7 on 2026-05-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_paymentrequest_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='send_notifications',
            field=models.BooleanField(default=True, help_text='Send notifications when this payment request is created.'),
        ),
    ]
