# Generated by Django 5.2.6 on 2026-07-27 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_membershipstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Date the application was submitted.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependant',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date membership was approved.', null=True),
        ),
    ]
