# Generated by Django 5.2.6 on 2026-07-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_member_applied_at_alter_dependant_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text='Automatically synchronised with related User email.', max_length=254, null=True, unique=True),
        ),
    ]
