# Generated by Django 5.2.6 on 2026-07-28 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
