# Generated by Django 5.2.6 on 2026-08-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_member_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes added by administrators during review.'),
        ),
        migrations.AddField(
            model_name='memberdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
