# Generated by Django 5.2.6 on 2026-08-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_memberdocument_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_portal_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date membership was activated.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('retired', 'Retired')], default='pending', max_length=16),
        ),
    ]
