# Generated by Django 5.2.6 on 2026-08-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_alter_member_is_portal_access_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_portal_access_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
