# Generated by Django 5.2.6 on 2026-08-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0041_alter_member_is_portal_access_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('retired', 'Retired')], default='pending', max_length=16),
        ),
    ]
