# Generated by Django 5.2.6 on 2026-08-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Private thumbnail generated for image documents. Access through the secure document thumbnail endpoint.', null=True, upload_to='member_documents/%Y/%m/thumbnails/'),
        ),
    ]
