# Generated by Django 5.2.6 on 2026-09-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_memberdocument_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimApprovalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_match_welfare_record', models.BooleanField(default=False)),
                ('telephone_matches_record', models.BooleanField(default=False)),
                ('confirmation_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('face_to_face', 'Face-to-face'), ('other', 'Other')], max_length=30)),
                ('confirmation_method_other', models.CharField(blank=True, max_length=255)),
                ('information_correct_declaration', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_verification', to='members.claim')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=200)),
                ('sort_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=34)),
                ('account_opened_date', models.DateField()),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='members.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimSubmissionDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_understood', models.BooleanField(default=False)),
                ('details_confirmed', models.BooleanField(default=False)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_declaration', to='members.claim')),
            ],
        ),
    ]
