# Generated by Django 5.2.6 on 2026-09-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_claim_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsubmissiondeclaration',
            name='next_of_kin_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
