# Generated by Django 5.2.6 on 2026-09-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0047_claimsubmissiondeclaration_next_of_kin_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependant',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dependant',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dependant',
            name='parent_status',
            field=models.CharField(blank=True, choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased'), ('UNKNOWN', 'Unknown')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='dependant',
            name='parent_type',
            field=models.CharField(blank=True, choices=[('MOTHER', 'Mother'), ('FATHER', 'Father')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dependant',
            name='sub_county_town',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widow / Widower'), ('SEPARATED', 'Separated')], max_length=16),
        ),
    ]
