# Generated by Django 5.2.6 on 2026-09-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0048_dependant_country_dependant_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependant',
            name='parent_status',
            field=models.CharField(blank=True, choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], max_length=12, null=True),
        ),
    ]
