# Generated by Django 5.2.6 on 2026-09-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_alter_dependant_parent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_audit_logs', 'Can view audit and activity logs'), ('can_export_audit_logs', 'Can export audit and activity logs')]},
        ),
    ]
