# Generated by Django 5.2.6 on 2026-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_alter_auditlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('member_status_change', 'Member Status Change'), ('dependant_update', 'Dependant Update'), ('nok_update', 'Next Of Kin Update'), ('payment_created', 'Payment Created'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('claim_approved', 'Claim Approved'), ('claim_rejected', 'Claim Rejected')], max_length=50),
        ),
    ]
